version: "3.8"

services:
  orders:
    build: ./services/orders
    container_name: orders_service
    ports:
      - "3000:3000"

  catalog:
    build: ./services/catalog
    container_name: catalog_service
    ports:
      - "5000:5000"
